### PR TITLE
Added option to remove all new lines

### PR DESCRIPTION
**Pull request by obduk**

### CODE REVIEW

**Comment by rmm5t** [comment]
Looks like a pretty clean PR, but could you help by elaborating on a specific use case where this is helpful. What kind of input are you receiving that you'd prefer not to allow newlines, but you're potentially receiving them anyway?

Also, I'm not sure about the term `:remove_new_lines` when it's really substituting newlines with a space, though I'm not sure what would covey this better. Removing newlines without replace them with spaces would be mostly crazy, and if we were just stripping them out, the existing `:regex` option would suffice.

However, _"newline"_ is one word (http://en.wikipedia.org/wiki/Newline), so I think the option should at least be renamed to `:remove_newlines`.

Lastly, should we also lump carriage returns (`\r`) in additional to line feeds (`\n`) here?

**Comment by obduk** [comment]
A few projects I have worked on have needed new lines removing (usually form text inputs that have had data come from other places, e.g. API). Although it can be done with the regex options, it just reads nicer. 

How about calling the options `:replace_newlines`

Good ida about the windows carriage returns, I will add that.

**Comment by rmm5t** [comment]
:+1:  `:replace_newlines`
:+1: windows carriage returns.

Could you please also update the README under the "Examples" section to cover this new option?

Will gladly pull this in afterwards. Thanks.

**Comment by obduk** [comment]
All updated.

**Comment by rmm5t** [comment]
Thanks for your work on this! Super clean. :beers:

**Comment by rmm5t** [comment]
**v1.7.0 just released**
https://rubygems.org/gems/strip_attributes

**Pull request merged**
