### PR TITLE
Support Rails 7

### PR DESCRIPTION
**Pull request by steveh**

### CODE REVIEW

**Comment by steveh** [comment]
Somehow missed #58

**Comment by rmm5t** [comment]
This PR looks cleaner than #58. 

@steveh Could you please re-open it. It looks like your branch was deleted.

**Comment by steveh** [comment]
Sure, done.

**Comment by rmm5t** [comment]
Thank you! I just merged this along with a fix of the CI workflows. I'll have a new release out later today. Cheers. 🍻

**Pull request merged**
